### ISSUE TITLE
not correct size of page in pdf

### ISSUE THREAD

**Issue by tonisimakov99** [cube-soft/Cube.Pdf#24]
![image](https://user-images.githubusercontent.com/31796662/142388872-7f9c867a-908b-424d-ad5b-f92cbc307b37.png)
![image](https://user-images.githubusercontent.com/31796662/142388954-2a025e97-b2df-46c4-9216-f11c84249f7f.png)
[shrek.pdf](https://github.com/cube-soft/Cube.Pdf/files/7561687/shrek.pdf)

**Comment by clown** [comment]
1. In the PDF specification, page size is expressed as a value based on 72 dpi.
2. Sometimes PDF holds rotation angle information separately from the page size.

Because of the above circumstances, you will need to calculate the display size with a program like the following. 

```cs
// using Cube.Pdf.Mixin; // for using GetViewSize() extended method

var your_dpi = 96.0; // depends on your display settings.
var size = page.GetViewSize();
var width = size.Width * your_dpi;
var height = size.Height * your_dpi;
```

The your_dpi value depends on your display settings. If the value of "Scale and layout" is set to 100%, your_dpi will be 96.

**Comment by tonisimakov99** [comment]
Thank you, it solved my problem
