### ISSUE TITLE
Printer to PDF Naming: If Document Contains a " - " everything before that is dismissed.

### ISSUE THREAD

**Issue by pjpks** [cube-soft/cube.pdf#41]
If my Document Name (in MS Word) is: "test - name.docx"
cubepdf Printer will only show "name.pdf" when saving/printing the Document.

**Comment by clown** [comment]
CubePDF determines the initial filename based on the "document name" obtained through the Windows virtual printer mechanism.

This name is set by the application that presses the print button.
Since many applications specify it in a format like "Application name - filename.ext", we have implemented a mechanism to trim some strings.

We will discuss this issue to see if there is a better way to trim.

**Comment by pjpks** [comment]
Thank you for the reply and explanation. as i was looking at diffrent solutions to my Problem, i found that clawPDF´s solution is:
a) userdefinable strings (cool!)
b) regarding this specific one the ones in the standard are as folows:
![grafik](https://github.com/cube-soft/cube.pdf/assets/126887898/1b654971-61dc-434e-884c-fb370bf13412)

in hopes that this is usefull information i greet sincerely

**Comment by clown** [comment]
We have improved the way to determine the initial filename in CubePDF 4.0.0.
https://www.cube-soft.com/cubepdf/
https://docs.cube-soft.jp/entry/2024/07/10/cubepdf-4.0.0-or-later

**Comment by pjpks** [comment]
Hi, i just tested, and can confirm that this change solved this specific problem :) Thanks a lot!
